---
:development:
  :collectd_base_path: "/var/lib/collectd"
  :server: Thin
  :port: 5252
  :engine: :Slim
:test:
  :server: Thin
  :port: 5252
  :engine: :Slim
:production:
  :collectd_base_path: "/var/lib/collectd"
  :server: Thin
  :port: 5252
  :engine: :Slim
