---
:development:
  - :url: "temperature-vs-pac"
    :name: "Température vs PAC"
    :yAxis0: "Température (°C)"
    :yAxis1: "Consommation PaC (W)"
    :series:
    - :name: "Pompe à chaleur"
      :host: "raspberrypi"
      :path: "current_cost-pac/power-power"
      :type: "area"
    - :name: "Salon"
      :host: "raspberrypi"
      :path: "current_cost-main/temperature-temperature"
      :type: "line"
    - :name: "Chambre Arthur"
      :host: "raspberrypi"
      :path: "rfxcom-chambre_arthur/temperature-temperature"
      :type: "line"
    - :name: "Chambre Olivia"
      :host: "raspberrypi"
      :path: "rfxcom-chambre_olivia/temperature-temperature"
      :type: "line"
